site_name: "Business Suite - Documentación"
site_description: "Documentación BRD y FSD - Business Suite"
site_author: "solis1408"
site_url: "https://solis1408.github.io/Business-Suite/"

docs_dir: docs

theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
    - navigation.indexes

extra_css:
  - assets/stylesheets/main-nav.css

extra_javascript:
  - assets/javascripts/main-nav.js

nav:
  - Inicio: index.md
  - Catálogos:
    - Gestión TI:
      - Inicio: Catalogos/Gestion-TI/documentacion/index.md
      - BRD: Catalogos/Gestion-TI/documentacion/BRD.md
      - FSD: Catalogos/Gestion-TI/documentacion/FSD.md
  - Procesos:
    - Gestión TI:
      - Inicio: Procesos/Gestion-TI/documentacion/index.md
      - BRD: Procesos/Gestion-TI/documentacion/BRD.md
      - FSD: Procesos/Gestion-TI/documentacion/FSD.md
  - Consultas:
    - Gestión TI:
      - ReporteForecast:
        - Inicio: Consultas/Gestion-TI/documentacion/reporte/index.md
        - BRD: Consultas/Gestion-TI/documentacion/reporte/BRD.md
        - FSD: Consultas/Gestion-TI/documentacion/reporte/FSD.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
